name: Ci Flow Check
on:
  push:
    branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checking out code
            uses: actions/Checkout@v5
          
          - name: Setting up Node Env
            uses: actions/setup-node@v3
            with:
                node-version: 24
         
          - name: Installing Dependencies
            run: npm install
         
          - name: Using Test Cases
            run: npm test

          - name: Log in to Docker Hub
            uses: docker/login-action@v2
            with:
               username: ${{ secrets.DOCKER_USERNAME }}
               password: ${{ secrets.DOCKER_PASSWORD  }}
          - name: Build Docker Image
            run: |
                BRANCH_NAME=${GITHUB_REF##*/}
                IMAGE_NAME="${ secrets.DOCKER_USERNAME }/ci-flow-check/${BRANCH_NAME}"
                docker build -t $IMAGE_NAME:latest .
          - name: Push Docker Image to Hub
            run: |
                BRANCH_NAME=${GITHUB_REF##*/}
                IMAGE_NAME="${ secrets.DOCKER_USERNAME }/ci-flow-check/${BRANCH_NAME}"
                docker push $IMAGE_NAME:latest
