name: Ci Flow Check
on:
  push:
    branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checking out code
            uses: actions/Checkout@v5
          
          - name: Setting up Node Env
            uses: actions/setup-node@v3
            with:
                node-version: 24
         
          - name: Installing Dependencies
            run: npm install
         
          - name: Using Test Cases
            run: npm test

